<template>
  <div>
    <div class="page-header">
      <div class="filter-bar">
        <input type="text" v-model="searchQuery" placeholder="Search by student name or reason..." class="search-input">
        <select v-model="selectedStatus" class="filter-select">
          <option value="">All Statuses</option>
          <option value="pending">Pending</option>
          <option value="resolved">Resolved</option>
        </select>
      </div>
      <!-- Alerts are typically generated by the system, so no "Add New Alert" button -->
    </div>

    <div class="table-container card">
      <div v-if="paginatedAlerts.length" class="table-responsive">
        <table>
          <thead>
            <tr>
              <th @click="sortBy('student_name')" class="sortable">
                Student Name <span v-if="sortKey === 'student_name'">{{ sortOrder === 'asc' ? '▲' : '▼' }}</span>
              </th>
              <th @click="sortBy('module_title')" class="sortable">
                Module <span v-if="sortKey === 'module_title'">{{ sortOrder === 'asc' ? '▲' : '▼' }}</span>
              </th>
              <th @click="sortBy('week_number')" class="sortable">
                Week <span v-if="sortKey === 'week_number'">{{ sortOrder === 'asc' ? '▲' : '▼' }}</span>
              </th>
              <th @click="sortBy('reason')" class="sortable">
                Reason <span v-if="sortKey === 'reason'">{{ sortOrder === 'asc' ? '▲' : '▼' }}</span>
              </th>
              <th @click="sortBy('created_at')" class="sortable">
                Created At <span v-if="sortKey === 'created_at'">{{ sortOrder === 'asc' ? '▲' : '▼' }}</span>
              </th>
              <th @click="sortBy('resolved')" class="sortable">
                Status <span v-if="sortKey === 'resolved'">{{ sortOrder === 'asc' ? '▲' : '▼' }}</span>
              </th>
              <th class="actions-header" v-if="authStore.isAdmin || authStore.isWellbeingOfficer">Actions</th>
            </tr>
          </thead>
          <tbody>
            <tr v-for="alert in paginatedAlerts" :key="alert.id">
              <td>{{ alert.student_name }}</td>
              <td>{{ alert.module_title }}</td>
              <td>{{ alert.week_number }}</td>
              <td>{{ alert.reason }}</td>
              <td>{{ new Date(alert.created_at).toLocaleDateString() }}</td>
              <td>
                <span :class="['status-badge', alert.resolved ? 'status-success' : 'status-danger']">
                  {{ alert.resolved ? 'Resolved' : 'Pending' }}
                </span>
              </td>
              <td class="action-buttons" v-if="authStore.isAdmin || authStore.isWellbeingOfficer">
                <button v-if="!alert.resolved" @click="resolveAlert(alert.id!)" class="btn-secondary btn-sm">Resolve</button>
                <button @click="deleteAlert(alert.id!)" class="btn-danger btn-sm">Delete</button>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
      <p v-else class="no-data-message">No alerts match your criteria.</p>
    </div>

    <div class="pagination-controls">
      <button @click="prevPage" :disabled="currentPage === 1" class="btn-secondary">Previous</button>
      <span class="page-info">Page {{ currentPage }} of {{ totalPages }}</span>
      <button @click="nextPage" :disabled="currentPage >= totalPages" class="btn-secondary">Next</button>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted, computed } from 'vue'
import { useAuthStore } from '@/stores/auth'
import { getAlerts, resolveAlert as apiResolveAlert, deleteAlert as apiDeleteAlert, type Alert } from '@/api/alertService'

const authStore = useAuthStore()

// Data
const allAlerts = ref<Alert[]>([])

// Filtering and Searching
const searchQuery = ref('')
const selectedStatus = ref('') // 'pending', 'resolved', or '' for all

// Sorting
const sortKey = ref<keyof Alert>('created_at')
const sortOrder = ref<'asc' | 'desc'>('desc') // Default to newest first

// Pagination
const currentPage = ref(1)
const itemsPerPage = ref(10)

// Computed properties for interactivity
const filteredAndSortedAlerts = computed(() => {
  let alerts = [...allAlerts.value]

  // Filter by search query
  if (searchQuery.value) {
    const lowerQuery = searchQuery.value.toLowerCase()
    alerts = alerts.filter(a =>
      a.student_name?.toLowerCase().includes(lowerQuery) ||
      a.reason.toLowerCase().includes(lowerQuery)
    )
  }

  // Filter by status
  if (selectedStatus.value === 'pending') {
    alerts = alerts.filter(a => !a.resolved)
  } else if (selectedStatus.value === 'resolved') {
    alerts = alerts.filter(a => a.resolved)
  }

  // Sort
  alerts.sort((a, b) => {
    const valA = a[sortKey.value]
    const valB = b[sortKey.value]
    if (valA === undefined || valB === undefined) return 0

    let comparison = 0;
    if (typeof valA === 'string' && typeof valB === 'string') {
      comparison = valA.localeCompare(valB);
    } else if (valA > valB) {
      comparison = 1;
    } else if (valA < valB) {
      comparison = -1;
    }
    return sortOrder.value === 'asc' ? comparison : -comparison;
  })

  return alerts
})

const totalPages = computed(() => {
  return Math.ceil(filteredAndSortedAlerts.value.length / itemsPerPage.value)
})

const paginatedAlerts = computed(() => {
  if (totalPages.value > 0 && currentPage.value > totalPages.value) {
    currentPage.value = totalPages.value;
  }
  const start = (currentPage.value - 1) * itemsPerPage.value
  const end = start + itemsPerPage.value
  return filteredAndSortedAlerts.value.slice(start, end)
})

// Methods
const fetchAlerts = async () => {
  try {
    const response = await getAlerts()
    allAlerts.value = response.data
  } catch (error: any) {
    console.error('Failed to fetch alerts:', error)
  }
}

const sortBy = (key: keyof Alert) => {
  if (sortKey.value === key) {
    sortOrder.value = sortOrder.value === 'asc' ? 'desc' : 'asc'
  } else {
    sortKey.value = key
    sortOrder.value = 'asc'
  }
}

const nextPage = () => {
  if (currentPage.value < totalPages.value) {
    currentPage.value++
  }
}

const prevPage = () => {
  if (currentPage.value > 1) {
    currentPage.value--
  }
}

const resolveAlert = async (id: number) => {
  if (confirm('Are you sure you want to mark this alert as resolved?')) {
    try {
      await apiResolveAlert(id)
      await fetchAlerts() // Refresh list
    } catch (error: any) {
      console.error('Failed to resolve alert:', error)
    }
  }
}

const deleteAlert = async (id: number) => {
  if (confirm('Are you sure you want to delete this alert? (Logical Delete)')) {
    try {
      await apiDeleteAlert(id)
      await fetchAlerts() // Refresh list
    } catch (error: any) {
      console.error('Failed to delete alert:', error)
    }
  }
}

onMounted(fetchAlerts)
</script>

<style scoped>
/* Reusing StudentsView.vue styles for consistency */
.page-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 2rem;
}

.filter-bar {
  display: flex;
  gap: 1rem;
}

.search-input, .filter-select {
  padding: 0.75rem 1rem;
  border: 1px solid var(--color-border);
  border-radius: 8px;
  background-color: var(--color-background);
  font-size: 1rem;
  transition: border-color 0.2s, box-shadow 0.2s;
}

.search-input {
  width: 300px;
}

.search-input:focus, .filter-select:focus {
  outline: none;
  border-color: var(--vt-c-indigo);
  box-shadow: 0 0 0 3px rgba(var(--vt-c-indigo-rgb), 0.2);
}

.table-container {
  background-color: var(--color-background);
  border-radius: 12px;
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.05);
  border: 1px solid var(--color-border);
  padding: 0;
}

.table-responsive {
  overflow-x: auto;
}

table {
  width: 100%;
  border-collapse: collapse;
}

th, td {
  padding: 1rem 1.5rem;
  text-align: left;
  vertical-align: middle;
}

thead tr {
  border-bottom: 1px solid var(--color-border-hover);
}

th {
  font-weight: 600;
  color: var(--color-text-light);
  text-transform: uppercase;
  font-size: 0.8rem;
  letter-spacing: 0.5px;
}

th.sortable {
  cursor: pointer;
  transition: color 0.2s;
}

th.sortable:hover {
  color: var(--color-heading);
}

th.sortable span {
  font-size: 0.9rem;
  margin-left: 0.5rem;
}

th.actions-header {
  text-align: right;
}

tbody tr {
  border-bottom: 1px solid var(--color-border);
}

tbody tr:last-child {
  border-bottom: none;
}

.action-buttons {
  display: flex;
  gap: 0.5rem;
  justify-content: flex-end;
}

.btn-sm {
  padding: 0.3rem 0.6rem;
  font-size: 0.8rem;
}

.no-data-message {
  text-align: center;
  padding: 4rem;
  color: var(--color-text-light);
  font-size: 1.1rem;
}

.pagination-controls {
  display: flex;
  justify-content: center;
  align-items: center;
  gap: 1rem;
  margin-top: 2rem;
}

.page-info {
  color: var(--color-text-light);
  font-size: 0.9rem;
}

.pagination-controls button:disabled {
  opacity: 0.5;
  cursor: not-allowed;
}

.status-badge {
  display: inline-block;
  padding: 0.3em 0.7em;
  border-radius: 12px; /* Pill shape */
  font-size: 0.8rem;
  font-weight: 600;
  color: white;
  text-transform: uppercase;
  letter-spacing: 0.5px;
}

.status-success {
  background-color: #10b981; /* Emerald */
}

.status-danger {
  background-color: #ef4444; /* Red */
}
</style>
