"""
Alert model definition for the application.

This module defines the `Alert` class, representing a system-generated alert
for a student, often related to their wellbeing or academic performance.
It inherits from `BaseModel` for common fields and includes specific attributes
like reason, associated module, and resolution status.
"""

from datetime import datetime
from .base_model import BaseModel

class Alert(BaseModel):
    """
    Represents an alert generated by the system for a student.

    Inherits from `BaseModel` for common fields such as `id`, `created_at`,
    and `is_active`. Alerts are typically triggered by specific conditions
    (e.g., low attendance, high stress) and can be resolved.
    """
    def __init__(self, id=None, student_id=None, module_id=None, week_number=None, reason=None, resolved=False, created_at=None, is_active=True, **kwargs):
        """
        Initializes an Alert instance.

        Args:
            id (int, optional): The unique identifier for the alert.
            student_id (int, optional): The ID of the student associated with this alert.
            module_id (int, optional): The ID of the module related to this alert (if applicable).
            week_number (int, optional): The academic week number when the alert was generated.
            reason (str, optional): A description of why the alert was generated.
            resolved (bool, optional): Status indicating if the alert has been addressed. Defaults to False.
            created_at (datetime, optional): The timestamp when the alert record was created. Defaults to current UTC time.
            is_active (bool, optional): Whether the alert record is active. Defaults to True.
            **kwargs: Additional keyword arguments passed to the BaseModel constructor.
        """
        super().__init__(id=id, created_at=created_at, is_active=is_active, **kwargs)
        self.student_id = student_id
        self.module_id = module_id
        self.week_number = week_number
        self.reason = reason
        self.resolved = resolved

    def to_dict(self) -> dict:
        """
        Converts the Alert object to a dictionary representation, including common base model fields.

        Returns:
            dict: A dictionary containing the alert's attributes suitable for JSON serialization.
        """
        data = super().to_dict() # Get common fields from BaseModel.
        data.update({
            'student_id': self.student_id,
            'module_id': self.module_id,
            'week_number': self.week_number,
            'reason': self.reason,
            'resolved': self.resolved,
        })
        return data

    @classmethod
    def from_row(cls, row) -> 'Alert':
        """
        Creates an Alert instance from a database row.

        This class method is used to reconstruct an Alert object from data
        retrieved from the database. It leverages `BaseModel.from_row`
        for common fields and then populates alert-specific attributes.

        Args:
            row: The database row, expected to be a dict-like object (e.g., `sqlite3.Row`).

        Returns:
            Alert: An Alert instance populated with data from the row, or None if the row is None.
        """
        if row is None:
            return None
        
        # Use BaseModel's from_row to parse common fields.
        base_instance = BaseModel.from_row(row)
        if not base_instance:
            return None

        row_dict = dict(row) # Convert row to dict for easier access to specific fields.
        
        # Extract alert-specific fields.
        student_id = row_dict.get('student_id')
        module_id = row_dict.get('module_id')
        week_number = row_dict.get('week_number')
        reason = row_dict.get('reason')
        resolved = bool(row_dict.get('resolved'))

        return cls(
            id=base_instance.id,
            student_id=student_id,
            module_id=module_id,
            week_number=week_number,
            reason=reason,
            resolved=resolved,
            is_active=base_instance.is_active,
            created_at=base_instance.created_at
        )

    def __repr__(self) -> str:
        """
        Returns a string representation of the Alert object, useful for debugging.
        """
        return f'<Alert ID: {self.id}, Student: {self.student_id}, Reason: "{self.reason[:20]}..."> '
